# Generated by Django 4.1.2 on 2022-11-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fileshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_email', models.EmailField(max_length=254, verbose_name='Enter Email')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
